import Head from 'next/head'
import Image from 'next/image'
import Four from '../components/home/Four'
import One from '../components/home/One'
import Three from '../components/home/Three'
import Two from '../components/home/Two'
import Footer from '../components/layout/Footer'
import Nav from '../components/layout/Nav'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div >
      <Head>
        <title>Besocial</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
      <One />
      <Two />
      <Three />
      <Four />
      <Footer />

    </div>
  )
}
